site_name: Maiko's Work
site_url: https://contexture-lab.com

theme:
  name: material
  language: ja
  palette:
    primary: blue
  font:
    text: false
    code: Roboto Mono

plugins:
  - search
  - glightbox

markdown_extensions:
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Contexture Lab.:
      - Overview: contexture/overview.md
      - Resume: contexture/resume.md
  - えるあの葉:
      - Overview: eru/concept.md
